---
title: "draft"
output: html_document
---

```{r}
library(ggplot2)
library(lubridate)
library(latex2exp)
library(svMisc)
library(rjson)
param.list <- fromJSON(file = "../config_files/xp_compare_cont.json") 
source("../scripts/estimators.R")
source("../scripts/utils.R")
```

```{r}
nulls_prop <- seq(param.list$nulls_proportion$begin, param.list$nulls_proportion$end,
                  by = param.list$nulls_proportion$by)  ##

mu1_range <- c(1.5)
```

```{r}
nb_methods = 1
for (mu1 in mu1_range){
  
  estimates <- matrix(data = NA, nrow = nb_methods * param.list$nb_run,  ##
                      ncol = length(nulls_prop), byrow = FALSE)  ##
  
  # rejections <- matrix(data = NA, nrow = (nb_methods + 2) * param.list$nb_run,  ##
  #                      ncol = length(nulls_prop), byrow = FALSE)  ##
  # 
  # power <- matrix(data = NA, nrow = (nb_methods + 2) * param.list$nb_run,  ##
  #                      ncol = length(nulls_prop), byrow = FALSE)  ##  
  
  for (i in 1:length(nulls_prop)) {  
    
    
    vec_1 <- c()
    # vec_2 <- c()
    # vec_3 <- c()
    
    for (j in 1:param.list$nb_run) {
      
      
      # generate data
      data <- generate_pvalues(param.list$m, mu1, nulls_prop[i])
      pvalues <- data$raw
      
      ## compute estimators for the different methods 
      new_poly_estim <- as.numeric(new_poly(pvalues, param.list$lambda, r=1) / param.list$m)
      # Storey_estim <- Storey(pvalues, param.list$lambda) / param.list$m
      # PC_estim <- PC_new_DM(pvalues) / param.list$m
      # PC_STOREY_estim <- PC_Storey(pvalues, param.list$lambda) / param.list$m
      # QUAD_estim <- quad_PC(pvalues) / param.list$m
      # PC_ZZD_estim <- PC_ZZD(pvalues, param.list$C, param.list$s) / param.list$m
      # QUAD_STOREY_estim <- Quad_Storey(pvalues, param.list$lambda) / param.list$m
      
      estimates_ <- c(as.numeric(new_poly_estim))
      
      ## Run adaptive BH procedure with each estimator and also raw BH and oracle adaptive BH
      # ABH_STOREY <- BH_proc(pvalues, alpha, TRUE, Storey_estim)
      # ABH_PC <- BH_proc(pvalues, alpha, TRUE, PC_estim)
      # ABH_PC_STOREY <- BH_proc(pvalues, alpha, TRUE, PC_STOREY_estim)
      # ABH_QUAD <- BH_proc(pvalues, alpha, TRUE, QUAD_estim)
      # ABH_PC_ZZD <- BH_proc(pvalues, alpha, TRUE, PC_ZZD_estim)
      # ABH_QUAD_STOREY <- BH_proc(pvalues, alpha, TRUE, QUAD_STOREY_estim)
      # BH <- BH_proc(pvalues, alpha)
      # oracle_BH <- BH_proc(pvalues, alpha, TRUE, nulls_prop[i])
      # 
      # rejections_ <- c(ABH_STOREY$k_hat, ABH_PC$k_hat, ABH_PC_STOREY$k_hat, ABH_QUAD$k_hat, ABH_PC_ZZD$k_hat, ABH_QUAD_STOREY$k_hat, BH$k_hat, oracle_BH$k_hat)
      # 
      # power_ <- c(
      #   proc_power(data$true_indices, ABH_STOREY$rej),
      #   proc_power(data$true_indices, ABH_PC$rej),
      #   proc_power(data$true_indices, ABH_PC_STOREY$rej),
      #   proc_power(data$true_indices, ABH_QUAD$rej),
      #   proc_power(data$true_indices, ABH_PC_ZZD$rej),
      #   proc_power(data$true_indices, ABH_QUAD_STOREY$rej),
      #   proc_power(data$true_indices, BH$rej),
      #   proc_power(data$true_indices, oracle_BH$rej)
      # )
      
      vec_1 <- c(vec_1, estimates_)
      # vec_2 <- c(vec_2, rejections_)
      # vec_3 <- c(vec_3, power_)
    }
    
    estimates[, i] <- vec_1
    # rejections[, i] <- vec_2
    # power[, i] <- vec_3
  }
}
```

```{r}
method = rep(c("new_poly"), param.list$nb_run) 

df_estimates <- data.frame(cbind(method, estimates))
df_estimates
```



```{r}
as.numeric(df_estimates$V2)
```

```{r}
pi0_seq <- seq(0.1, 0.9, 0.1)
pi0_1 = rep(pi0_seq, each = param.list$nb_run * nb_methods)
Estimator <- rep(c("new_poly"), length(pi0_seq))
mu_1 <- 1.5

estimators <- c(df_estimates$V2, df_estimates$V3, df_estimates$V4, df_estimates$V5, df_estimates$V6, df_estimates$V7, df_estimates$V8, df_estimates$V9, df_estimates$V10)
new_df <- data.frame(Estimator, estimators, pi0_1)
new_df$estimators <- as.numeric(estimators)
new_df$pi0 <- as.character(new_df$pi0_1)

plot_1 <- ggplot(new_df, aes(x=pi0, y=estimators, color=Estimator)) +
          
          geom_boxplot() +
          geom_segment(aes(x = as.character(0.05), y = 0.1, xend = as.character(0.15), yend = 0.1)) +
          geom_segment(aes(x = as.character(0.15), y = 0.2, xend = as.character(0.25), yend = 0.2)) +
          geom_segment(aes(x = as.character(0.25), y = 0.3, xend = as.character(0.35), yend = 0.3)) +
          geom_segment(aes(x = as.character(0.35), y = 0.4, xend = as.character(0.45), yend = 0.4)) +
          geom_segment(aes(x = as.character(0.45), y = 0.5, xend = as.character(0.55), yend = 0.5)) +
          geom_segment(aes(x = as.character(0.55), y = 0.6, xend = as.character(0.65), yend = 0.6)) +
          geom_segment(aes(x = as.character(0.65), y = 0.7, xend = as.character(0.75), yend = 0.7)) +
          geom_segment(aes(x = as.character(0.75), y = 0.8, xend = as.character(0.85), yend = 0.8)) +
          geom_segment(aes(x = as.character(0.85), y = 0.9, xend = as.character(0.95), yend = 0.9)) +
          scale_x_discrete(breaks=c("0.1","0.2","0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9"),
                           labels=c("0.1","0.2","0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9")) +
    
          # scale_colour_discrete(limits = c("STOREY", "PC", "PC_STOREY", "QUAD_STOREY"), 
          #                       labels = unname(TeX(c("$\\hat{m}_0^{Storey}$", "$\\hat{m}_0^{PC}$", "$\\hat{m}_0^{Poly}(1, 1/2)$", "$\\hat{m}_0^{Poly}(2, 1/2)$")))) +

          # theme(axis.text.x=element_blank(), axis.ticks.x=element_blank()) +
          labs(x = TeX("$\\pi_{0}$"), y = TeX("$\\hat{\\pi}_{0}$")) +
          theme(legend.text.align = 0)
  
  
  # plot_name = gsub(" " , "", paste("../../../xp_plot/simu/estimations/", gsub(" ", "_", paste("estimation_mu_1", as.character(mu_1), sep="_")), ".png"))
  # ggsave(filename = plot_name, plot = plot_1, width = 16, height = 10, units = "cm")
```

```{r}
plot_1
```



```{r}
new_df
```

