---
title: "pi0 on gwas data"
output: html_document
---

```{r}
library(data.table)
library(readxl)
library(readr)
library(dplyr)
library(ggplot2)
library(cowplot)
library(BiocParallel)

source("../scripts/estimators.R")


## load helper functions
for (f in list.files("../R", "\\.(r|R)$", full.names = TRUE)) {
    source(f)
}

# data and results directories
datdir <- "data"
resdir <- "results"
sbdir <- "../../results/GWAS"
dir.create(datdir, showWarnings = FALSE)
dir.create(resdir, showWarnings = FALSE)
dir.create(sbdir, showWarnings = FALSE)

# results files
resfile_N <- file.path(sbdir, paste0("bmi-samplesize-benchmark.rds"))
resfile_AF <- file.path(sbdir, paste0("bmi-maf-benchmark.rds"))
resfile_uninf <- file.path(sbdir, paste0("bmi-uninf-benchmark.rds"))

# set up parallel backend
# cores <- 8
# multicoreParam <- MulticoreParam(workers = cores)
```

```{r}
if (!file.exists(file.path(datdir, "BMI.SNPadjSMK.CombinedSexes.EuropeanOnly.txt"))) {
  # download.file(url = "http://portals.broadinstitute.org/collaboration/giant/images/3/3a/BMI.SNPadjSMK.zip", 
             # destfile = file.path(datdir, "BMI.SNPadjSMK.zip")) 
  unzip(file.path(datdir, "BMI.SNPadjSMK.zip"), exdir = datdir)
  file.remove(file.path(datdir,"BMI.SNPadjSMK.zip"))
  
  dfiles <- list.files(path = datdir, pattern = "BMI.SNPadjSMK.*.txt", 
                       full.names = TRUE)
  dfiles <- dfiles[!grepl("BMI.SNPadjSMK.CombinedSexes.EuropeanOnly.txt", dfiles)]
  file.remove(dfiles)
}
```

```{r}
# reffile <- file.path(datdir, "1000G_20101123_v3_GIANT_chr1_23_minimacnamesifnotRS_CEU_MAF0.01")
# if (!file.exists(paste0(reffile, ".fam"))) {
#     download.file("http://neurogenetics.qimrberghofer.edu.au/iSECA/1000G_20101123_v3_GIANT_chr1_23_minimacnamesifnotRS_CEU_MAF0.01.zip", 
#                   destfile = paste0(reffile, ".zip"))
#     unzip(paste0(reffile, ".zip"), exdir = datdir)
#     file.remove(paste0(reffile, ".zip"))
# }
```

```{r}
bmi <- fread(file.path(datdir, "BMI.SNPadjSMK.CombinedSexes.EuropeanOnly.txt"),
             header = TRUE)
dim(bmi)
```

```{r}
head(bmi)
```

```{r}
pvalues <- bmi$p_value
hist(pvalues)
```

```{r}
lambda = 0.5
m = length(pvalues)
```

```{r}
storey_estim <- Storey(pvalues, lambda) / m
pc_estim <- PC_new_DM(pvalues) / m
# pc_zzd_estim <- PC_ZZD(pvalues, C, s) / m

storey_pc_estim <- PC_Storey(pvalues, lambda) / m
storey_quad_estim <- Quad_Storey(pvalues, lambda) / m

quad_estim <- quad_PC(pvalues) / m

```

```{r}
data= matrix(c(storey_estim, pc_estim, storey_pc_estim, storey_quad_estim, quad_estim), ncol=5, byrow=TRUE)
colnames(data) = c('Storey','PC', 'Storey-PC', "Storey-Quad", "Quad")
as.table(data)
```

