---
title: "xp plot"
output: html_document
---
```{r}
library(ggplot2)
library(lubridate)
library(dplyr)
library(latex2exp)
library(RColorBrewer)
library(tidyverse)
```

```{r}
nb_run = 1000
nb_methods = 6
pi0_seq <- seq(0.1, 0.9, 0.1)
mu1_seq <- c(0, 0.5, 1, 1.5, 2, 2.5, 3)
```


```{r}
file_names <- c(
"../../xp_data/FET/estimators/data_estimates_non_nulls_proportion_study_2023-03-16_15:03:30.csv"
)
```

```{r}
pi0 = rep(pi0_seq, each = nb_run * nb_methods)
test <- read.csv(file_names[1])
methods <- rep(test$method, length(pi0_seq))
```

```{r}
for (i in 1:1) {
  
  mu_1 <- mu1_seq[i]

  df <- read.csv(file_names[1])
 
  estimators <- c(df$V2, df$V3, df$V4, df$V5, df$V6, df$V7, df$V8, df$V9, df$V10)  
  new_df <- data.frame(methods, estimators, pi0)
  new_df$pi0 <- as.character(new_df$pi0)

  plot_ <- ggplot(new_df, aes(x=pi0, y=estimators, color=methods)) +
          geom_boxplot() 

          # scale_colour_discrete(limits = c("STOREY", "PC_ZZD", "PC_DM", "HYB_PC_STO", "PC_QUAD", "HYB_Quad_Storey")) 
   
  
  # plot_name = gsub(" " , "", paste("../../xp_plot/", gsub(" ", "_", paste("estimation_vary_mu_1", as.character(mu_1), sep="_")), ".png"))
  # ggsave(filename = plot_name, plot = plot_, width = 16, height = 10, units = "cm")
  
}
```

```{r}
df <- read.csv(file_names[2])
df
estimators <- c(df$V2, df$V3, df$V4, df$V5, df$V6, df$V7, df$V8, df$V9, df$V10)  
new_df <- data.frame(methods, estimators, pi0)
new_df
```


```{r}
plot_
```



```{r}
file_names_2 <- c(
"../../xp_data/gaussian/rejections/data_rejections_mu1_0_nulls_proportion_study_2023-03-16_08:52:22.csv",
"../../xp_data/gaussian/rejections/data_rejections_mu1_0.5_nulls_proportion_study_2023-03-16_08:54:08.csv",
"../../xp_data/gaussian/rejections/data_rejections_mu1_1_nulls_proportion_study_2023-03-16_08:56:51.csv",
"../../xp_data/gaussian/rejections/data_rejections_mu1_1.5_nulls_proportion_study_2023-03-16_08:59:46.csv",
"../../xp_data/gaussian/rejections/data_rejections_mu1_2_nulls_proportion_study_2023-03-16_09:02:37.csv",
"../../xp_data/gaussian/rejections/data_rejections_mu1_2.5_nulls_proportion_study_2023-03-16_09:05:25.csv",
"../../xp_data/gaussian/rejections/data_rejections_mu1_3_nulls_proportion_study_2023-03-16_09:08:11.csv"
)
```


```{r}
pi0 = rep(pi0_seq, each = nb_run * (nb_methods + 2))
test <- read.csv(file_names_2[1])
methods <- rep(test$method, length(pi0_seq))

```


```{r}
for (i in 1:length(file_names_2)) {
  
  mu_1 <- mu1_seq[i]

  df <- read.csv(file_names_2[i])
 
  rejections <- c(df$V2, df$V3, df$V4, df$V5, df$V6, df$V7, df$V8, df$V9, df$V10, df$V11)  
  new_df <- data.frame(methods, rejections, pi0)

  plot_ <- ggplot(new_df, aes(x=pi0, y=rejections, color=methods)) +
          geom_boxplot() +
          facet_wrap(~pi0, scale="free") +
          theme(axis.text.x=element_blank(), axis.ticks.x=element_blank()) +
          scale_colour_discrete(limits = c("STOREY", "PC_ZZD", "PC_DM", "HYB_PC_STO", "PC_QUAD", "HYB_Quad_Storey")) +
          labs(x = TeX("$\\pi_{0}$"), y = "Rejections for plug-in BH")

  plot_name = gsub(" " , "", paste("../../xp_plot/", gsub(" ", "_", paste("rejections_vary_mu_1", as.character(mu_1), sep="_")), ".png"))
  ggsave(filename = plot_name, plot = plot_, width = 16, height = 10, units = "cm")
}
```

#---------------------------------------------------------------------------------------------------------------------------------------------------

```{r}
file_names_3 <- c(
"../../xp_data/FET/estimators/data_estimates_non_nulls_proportion_study_2023-03-16_15:03:30.csv"
)
```

```{r}
pi0 = 1 - rep(pi0_seq, each = nb_run * nb_methods )
test <- read.csv(file_names_3[1])
methods <- rep(test$method, length(pi0_seq))

```

```{r}
for (i in 1:length(file_names_3)) {

  df <- read.csv(file_names_3[i])
 
  rejections <- c(df$V2, df$V3, df$V4, df$V5, df$V6, df$V7, df$V8, df$V9, df$V10, df$V11)  
  new_df <- data.frame(methods, rejections, pi0)
  # print(new_df)
  new_df <- new_df %>% filter(methods != "PC") %>% filter(methods != "PC_midp") %>% filter(methods != "STOREY_RANDOM") %>% filter(methods != "PC_RANDOM")
  new_df$pi0 <- as.character(new_df$pi0)
  # print(new_df)

  plot_ <- ggplot(new_df, aes(x=pi0, y=rejections, color=methods)) +
          geom_boxplot() +
          # facet_wrap(~pi0, scale="free") +
          scale_x_discrete(limits=factor(seq(0.1, 0.9, 0.1))) +
          # geom_segment(aes(x = as.character(0.05), y = 0.1, xend = as.character(0.15), yend = 0.1), color = "black", size = 0.8) +
          # geom_segment(aes(x = as.character(0.15), y = 0.2, xend = as.character(0.25), yend = 0.2), color = "black", size = 0.8) +
          # geom_segment(aes(x = as.character(0.25), y = 0.3, xend = as.character(0.35), yend = 0.3), color = "black", size = 0.8) +
          # geom_segment(aes(x = as.character(0.35), y = 0.4, xend = as.character(0.45), yend = 0.4), color = "black", size = 0.8) +
          # geom_segment(aes(x = as.character(0.45), y = 0.5, xend = as.character(0.55), yend = 0.5), color = "black", size = 0.8) +
          # geom_segment(aes(x = as.character(0.55), y = 0.6, xend = as.character(0.65), yend = 0.6), color = "black", size = 0.8) +
          # geom_segment(aes(x = as.character(0.65), y = 0.7, xend = as.character(0.75), yend = 0.7), color = "black", size = 0.8) +
          # geom_segment(aes(x = as.character(0.75), y = 0.8, xend = as.character(0.85), yend = 0.8), color = "black", size = 0.8) +
          # geom_segment(aes(x = as.character(0.85), y = 0.9, xend = as.character(0.95), yend = 0.9), color = "black", size = 0.8) +
          theme( axis.ticks.x=element_blank()) +
          
          labs(x = TeX("$\\pi_{0}$"), y = TeX("$\\hat{\\pi}_{0}$"))

  plot_name = gsub(" " , "", paste("../../xp_plot/simu/", gsub(" ", "_", paste("estimators_on_FET",  now(), sep="_")), ".png"))
  ggsave(filename = plot_name, plot = plot_, width = 16, height = 10, units = "cm")
}
```

```{r}
plot_
```

